export const secretSymbol = "_";

export const alphabet = [
  ["а", "vowel"],
  ["б", "consonant"],
  ["в", "consonant"],
  ["г", "consonant"],
  ["д", "consonant"],
  ["е", "vowel"],
  ["ё", "vowel"],
  ["ж", "consonant"],
  ["з", "consonant"],
  ["и", "vowel"],
  ["й", "consonant"],
  ["к", "consonant"],
  ["л", "consonant"],
  ["м", "consonant"],
  ["н", "consonant"],
  ["о", "vowel"],
  ["п", "consonant"],
  ["р", "consonant"],
  ["с", "consonant"],
  ["т", "consonant"],
  ["у", "vowel"],
  ["ф", "consonant"],
  ["х", "consonant"],
  ["ц", "consonant"],
  ["ч", "consonant"],
  ["ш", "consonant"],
  ["щ", "consonant"],
  ["ъ", ""],
  ["ы", "vowel"],
  ["ь", ""],
  ["э", "vowel"],
  ["ю", "vowel"],
  ["я", "vowel"]
];
