export const secretSymbol = "_";

export const alphabet = [
  ["а", "vowel", false],
  ["б", "consonant", false],
  ["в", "consonant", false],
  ["г", "consonant", false],
  ["д", "consonant", false],
  ["е", "vowel", false],
  ["ё", "vowel", false],
  ["ж", "consonant", false],
  ["з", "consonant", false],
  ["и", "vowel", false],
  ["й", "consonant", false],
  ["к", "consonant", false],
  ["л", "consonant", false],
  ["м", "consonant", false],
  ["н", "consonant", false],
  ["о", "vowel", false],
  ["п", "consonant", false],
  ["р", "consonant", false],
  ["с", "consonant", false],
  ["т", "consonant", false],
  ["у", "vowel", false],
  ["ф", "consonant", false],
  ["х", "consonant", false],
  ["ц", "consonant", false],
  ["ч", "consonant", false],
  ["ш", "consonant", false],
  ["щ", "consonant", false],
  ["ъ", "", false],
  ["ы", "vowel", false],
  ["ь", "", false],
  ["э", "vowel", false],
  ["ю", "vowel", false],
  ["я", "vowel", false]
];
